// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	models "github.com/azaliaz/bookly/book-service/internal/domain/models"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// DeleteBooks provides a mock function with given fields:
func (_m *Storage) DeleteBooks() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteBooks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBook provides a mock function with given fields: _a0
func (_m *Storage) GetBook(_a0 string) (models.Book, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetBook")
	}

	var r0 models.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Book, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) models.Book); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Book)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBooks provides a mock function with given fields:
func (_m *Storage) GetBooks() ([]models.Book, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBooks")
	}

	var r0 []models.Book
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Book, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Book); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Book)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}


// SaveBook provides a mock function with given fields: _a0
func (_m *Storage) SaveBook(_a0 models.Book) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SaveBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Book) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveBooks provides a mock function with given fields: _a0
func (_m *Storage) SaveBooks(_a0 []models.Book) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SaveBooks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]models.Book) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}


// SetDeleteStatus provides a mock function with given fields: _a0
func (_m *Storage) SetDeleteStatus(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetDeleteStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}


// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
